version: 2
updates:
  - package-ecosystem: github-actions
    cooldown:
      default-days: 7
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: chore
      include: scope
    groups:
      github-actions:
        patterns:
          - "*"
