import copy
import importlib.util
import json
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TOKENS = ROOT / ".quirk" / "design" / "tokens.json"


def load_module():
    spec = importlib.util.spec_from_file_location("design_tokens", ROOT / "scripts" / "design_tokens.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


class DesignTokenTests(unittest.TestCase):
    def setUp(self):
        self.module = load_module()
        self.data = json.loads(TOKENS.read_text(encoding="utf-8"))

    def valid(self):
        return copy.deepcopy(self.data)

    def assert_rejected(self, data, fragment):
        with self.assertRaises(self.module.TokenError) as caught:
            self.module.validate(data)
        self.assertIn(fragment, str(caught.exception))

    def test_seed_tokens_validate(self):
        self.assertEqual(self.module.main(["validate", str(TOKENS)]), 0)

    def test_seed_is_candidate_with_implementation_owner_and_no_authority(self):
        quirk = self.data["$extensions"]["quirk"]
        self.assertEqual(quirk["status"], "candidate")
        self.assertEqual(quirk["authority_effect"], "none")
        self.assertEqual(quirk["implementation_owner"], "Quirk-Systems/quirk-design")

    def test_aliases_resolve_and_inherit_type(self):
        tokens, resolved = self.module.validate(self.valid())
        self.assertEqual(resolved["color.text.default"], resolved["color.ink"])
        self.assertEqual(tokens["color.text.default"]["type"], "color")

    def test_css_projection_is_deterministic_and_prefixed(self):
        tokens, resolved = self.module.validate(self.valid())
        css = self.module.emit_css(tokens, resolved, "quirk")
        self.assertEqual(css, self.module.emit_css(tokens, resolved, "quirk"))
        self.assertIn("--quirk-color-signal: #c8451f;", css)
        self.assertIn("--quirk-space-4: 16px;", css)
        self.assertIn("--quirk-motion-ease-standard: cubic-bezier(0.2, 0, 0, 1);", css)
        self.assertIn('--quirk-font-family-mono: "JetBrains Mono", ui-monospace, monospace;', css)
        self.assertTrue(css.startswith("/* Generated by scripts/design_tokens.py"))

    def test_json_projection_is_flat_and_sorted(self):
        tokens, resolved = self.module.validate(self.valid())
        flat = json.loads(self.module.emit_json(tokens, resolved))
        self.assertEqual(list(flat), sorted(flat))
        self.assertEqual(flat["color.ink"], {"type": "color", "value": "#141210"})

    def test_missing_alias_target_fails(self):
        data = self.valid()
        data["color"]["text"]["default"]["$value"] = "{color.nope}"
        self.assert_rejected(data, "alias target does not exist")

    def test_alias_cycle_fails(self):
        data = self.valid()
        data["color"]["ink"]["$value"] = "{color.text.default}"
        self.assert_rejected(data, "alias cycle")

    def test_uppercase_hex_fails(self):
        data = self.valid()
        data["color"]["signal"]["$value"] = "#C8451F"
        self.assert_rejected(data, "color must be lowercase")

    def test_dimension_without_unit_fails(self):
        data = self.valid()
        data["space"]["4"]["$value"] = 16
        self.assert_rejected(data, "dimension must be")

    def test_bad_group_name_fails(self):
        data = self.valid()
        data["Color"] = {"$type": "color", "x": {"$value": "#000000"}}
        self.assert_rejected(data, "lowercase kebab-case")

    def test_unknown_token_key_fails(self):
        data = self.valid()
        data["color"]["ink"]["$note"] = "x"
        self.assert_rejected(data, "unknown token keys")

    def test_unknown_type_fails(self):
        data = self.valid()
        data["color"]["$type"] = "colour"
        self.assert_rejected(data, "unknown $type")

    def test_token_without_type_fails(self):
        data = self.valid()
        data["misc"] = {"thing": {"$value": 1}}
        self.assert_rejected(data, "no $type")

    def test_authority_effect_must_be_none(self):
        data = self.valid()
        data["$extensions"]["quirk"]["authority_effect"] = "canonical"
        self.assert_rejected(data, "authority_effect must be none")

    def test_bezier_x_out_of_range_fails(self):
        data = self.valid()
        data["motion"]["ease"]["standard"]["$value"] = [1.2, 0, 0, 1]
        self.assert_rejected(data, "cubicBezier")


if __name__ == "__main__":
    unittest.main()
