import copy
import importlib.util
import json
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA = ROOT / ".quirk" / "schemas" / "portfolio-registry.schema.json"
REGISTRY = ROOT / ".quirk" / "repositories.json"


def load(name):
    spec = importlib.util.spec_from_file_location(name, ROOT / "scripts" / f"{name}.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


class PortfolioRegistryTests(unittest.TestCase):
    def setUp(self):
        self.validator = load("validate_portfolio")
        self.report = load("portfolio_report")
        self.schema = json.loads(SCHEMA.read_text(encoding="utf-8"))
        self.data = json.loads(REGISTRY.read_text(encoding="utf-8"))

    def valid(self):
        return copy.deepcopy(self.data)

    def assert_rejected(self, data, fragment):
        with self.assertRaises(self.validator.PortfolioError) as caught:
            self.validator.validate_portfolio(data, self.schema)
        self.assertIn(fragment, str(caught.exception))

    def test_registry_is_valid(self):
        self.assertEqual(self.validator.main([]), 0)

    def test_projection_is_in_sync(self):
        self.assertEqual(self.report.main(["--check"]), 0)

    def test_report_is_deterministic_and_marked_generated(self):
        rendered = self.report.render(self.data)
        self.assertEqual(rendered, self.report.render(self.data))
        self.assertIn("Generated by scripts/portfolio_report.py", rendered)
        self.assertIn("Authority effect: **none**", rendered)
        self.assertIn("**not** inferred from names", rendered)

    def test_check_detects_drift(self):
        with tempfile.TemporaryDirectory() as tmp:
            output = Path(tmp) / "PORTFOLIO.md"
            output.write_text("stale", encoding="utf-8")
            self.assertEqual(self.report.main(["--check", "--output", str(output)]), 1)
            self.assertEqual(self.report.main(["--output", str(output)]), 0)
            self.assertEqual(self.report.main(["--check", "--output", str(output)]), 0)

    def test_observed_entries_record_facts_only(self):
        for entry in self.data.get("observed_unclassified", []):
            self.assertEqual(entry["status"], "OBSERVED_UNCLASSIFIED")
            for forbidden in ("primary_class", "lifecycle", "purpose", "canonical", "owner"):
                self.assertNotIn(forbidden, entry, entry["repository"])

    def test_existing_classified_entries_are_unchanged_in_shape(self):
        names = {entry["repository"] for entry in self.data["repositories"]}
        for required in ("Quirk-Systems/.github", "Quirk-Systems/.github-private", "Quirk-Systems/project-scaffold",
                         "Quirk-Systems/quirk-os", "Quirk-Systems/quirk-core"):
            self.assertIn(required, names)

    def test_unknown_key_fails_closed(self):
        data = self.valid()
        data["repositories"][0]["health_score"] = 10
        self.assert_rejected(data, "unknown keys")

    def test_duplicate_repository_fails(self):
        data = self.valid()
        data["repositories"].append(copy.deepcopy(data["repositories"][0]))
        self.assert_rejected(data, "unique")

    def test_observed_entry_that_is_also_classified_fails(self):
        data = self.valid()
        data["observed_unclassified"].append({
            "repository": "Quirk-Systems/.github", "visibility": "public",
            "created_at": "2026-01-12T13:05:03Z", "observed_at": "2026-09-19", "status": "OBSERVED_UNCLASSIFIED",
        })
        data["observed_unclassified"].sort(key=lambda e: e["repository"].casefold())
        data["observation"]["total_observed"] += 1
        self.assert_rejected(data, "duplicate classified entries")

    def test_observed_entry_cannot_claim_classification(self):
        data = self.valid()
        data["observed_unclassified"][0]["status"] = "active"
        self.assert_rejected(data, "must equal")

    def test_total_observed_must_reconcile(self):
        data = self.valid()
        data["observation"]["total_observed"] += 1
        self.assert_rejected(data, "total_observed")

    def test_unsorted_observed_entries_fail(self):
        data = self.valid()
        data["observed_unclassified"].reverse()
        self.assert_rejected(data, "sorted")

    def test_missing_canon_repository_fails(self):
        data = self.valid()
        data["repositories"] = [e for e in data["repositories"] if e["repository"] != "Quirk-Systems/.github-private"]
        self.assert_rejected(data, "must be registered")


if __name__ == "__main__":
    unittest.main()
