import copy
import importlib.util
import json
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA = ROOT / ".quirk" / "schemas" / "repository-inventory.schema.json"
REGISTRY = ROOT / ".quirk" / "repositories.json"


def load(name):
    spec = importlib.util.spec_from_file_location(name, ROOT / "scripts" / f"{name}.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


class PortfolioRegistryTests(unittest.TestCase):
    def setUp(self):
        self.validator = load("validate_portfolio")
        self.report = load("portfolio_report")
        self.schema = json.loads(SCHEMA.read_text(encoding="utf-8"))
        self.data = json.loads(REGISTRY.read_text(encoding="utf-8"))

    def valid(self):
        return copy.deepcopy(self.data)

    def assert_rejected(self, data, fragment):
        with self.assertRaises(self.validator.PortfolioError) as caught:
            self.validator.validate_portfolio(data, self.schema)
        self.assertIn(fragment, str(caught.exception))

    def test_registry_is_valid(self):
        self.assertEqual(self.validator.main([]), 0)

    def test_projection_is_in_sync(self):
        self.assertEqual(self.report.main(["--check"]), 0)

    def test_report_is_deterministic_and_marked_generated(self):
        rendered = self.report.render(self.data)
        self.assertEqual(rendered, self.report.render(self.data))
        self.assertIn("Generated by scripts/portfolio_report.py", rendered)
        self.assertIn("Authority effect: **none**", rendered)
        self.assertIn("Snapshot: `2026-08-21`", rendered)
        self.assertIn("Decisions awaiting an owner", rendered)
        self.assertIn("bryansayler/quirk-commerce", rendered)

    def test_check_detects_drift(self):
        with tempfile.TemporaryDirectory() as tmp:
            output = Path(tmp) / "PORTFOLIO.md"
            output.write_text("stale", encoding="utf-8")
            self.assertEqual(self.report.main(["--check", "--output", str(output)]), 1)
            self.assertEqual(self.report.main(["--output", str(output)]), 0)
            self.assertEqual(self.report.main(["--check", "--output", str(output)]), 0)

    def test_scope_counts_match_snapshot(self):
        organization = {entry["repository"] for entry in self.data["repositories"] if entry["scope"] == "organization"}
        adjacent = {entry["repository"] for entry in self.data["repositories"] if entry["scope"] == "adjacent"}
        self.assertEqual(len(organization), self.data["scope"]["expected_organization_repository_count"])
        self.assertEqual(len(adjacent), self.data["scope"]["expected_adjacent_repository_count"])

    def test_unknown_key_fails_closed(self):
        data = self.valid()
        data["repositories"][0]["health_score"] = 10
        self.assert_rejected(data, "unexpected fields: health_score")

    def test_duplicate_repository_fails(self):
        data = self.valid()
        data["repositories"].append(copy.deepcopy(data["repositories"][0]))
        self.assert_rejected(data, "repositories must be unique")

    def test_missing_required_repository_fails(self):
        data = self.valid()
        data["repositories"] = [entry for entry in data["repositories"] if entry["repository"] != "Quirk-Systems/.github-private"]
        self.assert_rejected(data, "missing organization repositories: Quirk-Systems/.github-private")

    def test_scope_partition_drift_fails(self):
        data = self.valid()
        data["repositories"][-1]["scope"] = "organization"
        self.assert_rejected(data, "unexpected organization repositories")


if __name__ == "__main__":
    unittest.main()
