import copy
import importlib.util
import json
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA = ROOT / ".quirk" / "schemas" / "repository-inventory.schema.json"
REGISTRY = ROOT / ".quirk" / "repositories.json"


def load(name):
    spec = importlib.util.spec_from_file_location(name, ROOT / "scripts" / f"{name}.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


class PortfolioRegistryTests(unittest.TestCase):
    def setUp(self):
        self.validator = load("validate_portfolio")
        self.topology = load("validate_topology")
        self.report = load("portfolio_report")
        self.schema = json.loads(SCHEMA.read_text(encoding="utf-8"))
        self.data = json.loads(REGISTRY.read_text(encoding="utf-8"))

    def valid(self):
        return copy.deepcopy(self.data)

    def assert_rejected(self, data, fragment, schema=None):
        with self.assertRaises(self.validator.PortfolioError) as caught:
            self.validator.validate_portfolio(data, schema or self.schema)
        self.assertIn(fragment, str(caught.exception))

    def test_registry_is_valid(self):
        self.assertEqual(self.validator.main([]), 0)

    def test_projection_is_in_sync(self):
        self.assertEqual(self.report.main(["--check"]), 0)

    def test_report_is_deterministic_and_marked_generated(self):
        rendered = self.report.render(self.data)
        self.assertEqual(rendered, self.report.render(self.data))
        self.assertIn("Generated by scripts/portfolio_report.py", rendered)
        self.assertIn("Authority effect: **none**", rendered)
        self.assertIn("Snapshot: `2026-08-21`", rendered)
        self.assertIn("Decisions awaiting an owner", rendered)
        self.assertIn("bryansayler/quirk-commerce", rendered)

    def test_check_detects_drift(self):
        with tempfile.TemporaryDirectory() as tmp:
            output = Path(tmp) / "PORTFOLIO.md"
            output.write_text("stale", encoding="utf-8")
            self.assertEqual(self.report.main(["--check", "--output", str(output)]), 1)
            self.assertEqual(self.report.main(["--output", str(output)]), 0)
            self.assertEqual(self.report.main(["--check", "--output", str(output)]), 0)

    def test_scope_counts_and_sets_match_snapshot(self):
        organization = {entry["repository"] for entry in self.data["repositories"] if entry["scope"] == "organization"}
        adjacent = {entry["repository"] for entry in self.data["repositories"] if entry["scope"] == "adjacent"}
        self.assertEqual(len(organization), self.data["scope"]["expected_organization_repository_count"])
        self.assertEqual(len(adjacent), self.data["scope"]["expected_adjacent_repository_count"])
        self.assertSetEqual(organization, self.topology.EXPECTED_ORGANIZATION_REPOSITORIES)
        self.assertSetEqual(adjacent, self.topology.EXPECTED_ADJACENT_REPOSITORIES)

    def test_unknown_key_fails_closed(self):
        data = self.valid()
        data["repositories"][0]["health_score"] = 10
        self.assert_rejected(data, "unknown keys ['health_score']")

    def test_duplicate_repository_fails(self):
        data = self.valid()
        data["repositories"].append(copy.deepcopy(data["repositories"][0]))
        schema = copy.deepcopy(self.schema)
        schema["properties"]["repositories"]["maxItems"] = 20
        self.assert_rejected(data, "repositories must be unique", schema=schema)

    def test_extra_repository_fails_schema_max_items(self):
        data = self.valid()
        data["repositories"].append(copy.deepcopy(data["repositories"][0]))
        self.assert_rejected(data, "needs at most 19 items")

    def test_missing_required_repository_fails(self):
        data = self.valid()
        data["repositories"] = [entry for entry in data["repositories"] if entry["repository"] != "Quirk-Systems/.github-private"]
        schema = copy.deepcopy(self.schema)
        schema["properties"]["repositories"]["minItems"] = 18
        schema["properties"]["repositories"]["maxItems"] = 18
        schema["properties"]["repositories"]["allOf"] = [
            clause
            for clause in schema["properties"]["repositories"]["allOf"]
            if clause["contains"]["properties"]["repository"]["const"] != "Quirk-Systems/.github-private"
        ]
        self.assert_rejected(data, "missing organization repositories: Quirk-Systems/.github-private", schema=schema)

    def test_missing_required_repository_fails_schema_contains(self):
        data = self.valid()
        data["repositories"] = [entry for entry in data["repositories"] if entry["repository"] != "Quirk-Systems/.github-private"]
        schema = copy.deepcopy(self.schema)
        schema["properties"]["repositories"]["minItems"] = 18
        schema["properties"]["repositories"]["maxItems"] = 18
        self.assert_rejected(data, "fewer than 1 items match the contains schema", schema=schema)

    def test_scope_partition_drift_fails(self):
        data = self.valid()
        data["repositories"][-1]["scope"] = "organization"
        self.assert_rejected(data, "unexpected organization repositories")

    def test_empty_adjacency_rule_fails(self):
        data = self.valid()
        data["scope"]["adjacent_repository_selection_rule"] = ""
        self.assert_rejected(data, "adjacent_repository_selection_rule")

    def test_whitespace_adjacency_rule_fails(self):
        data = self.valid()
        data["scope"]["adjacent_repository_selection_rule"] = "   "
        self.assert_rejected(data, "adjacent_repository_selection_rule")

    def test_owner_identified_without_name_fails(self):
        data = self.valid()
        data["repositories"][0]["owner"] = {"state": "identified"}
        self.assert_rejected(data, "missing required keys ['name']")

    def test_reserved_lifecycle_requires_reservation_class(self):
        data = self.valid()
        reserved = next(entry for entry in data["repositories"] if entry["lifecycle"] == "reserved")
        reserved["primary_class"] = "canon"
        self.assert_rejected(data, "primary_class")

    def test_table_cells_escape_pipes_and_newlines(self):
        data = self.valid()
        entry = data["repositories"][0]
        entry["canonical_responsibility"] = "left | right\nnext line"
        entry["deployment_security_boundary"] = "a|b\r\nc"
        rendered = self.report.render(data)
        self.assertIn("left \\| right<br>next line", rendered)
        self.assertIn("a\\|b<br>c", rendered)
        self.assertNotIn("left | right", rendered)


if __name__ == "__main__":
    unittest.main()
