#!/usr/bin/env python3
"""Render docs/PORTFOLIO.md from .quirk/repositories.json.

The Markdown file is a projection. The registry is the source. `--check`
fails when the committed projection differs from what the registry renders,
so the two cannot drift. Standard library only; deterministic output.
"""

import argparse
import json
import sys
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / ".quirk" / "repositories.json"
OUTPUT = ROOT / "docs" / "PORTFOLIO.md"
GITHUB = "https://github.com/"


def link(repository):
    return f"[`{repository}`]({GITHUB}{repository})"


def render(data):
    lines = [
        "# Quirk Systems portfolio",
        "",
        "<!-- Generated by scripts/portfolio_report.py from .quirk/repositories.json. Do not edit; edit the registry. -->",
        "",
        f"Registry version: `{data['registry_version']}`  ",
        f"Registry status: `{data['status']}`  ",
        f"Registry updated: {data['updated_at']}  ",
        "Authority effect: **none**. This page projects the registry; it classifies nothing by itself.",
        "",
    ]
    repos = data["repositories"]
    observed = data.get("observed_unclassified", [])
    observation = data.get("observation")

    lines += ["## Summary", ""]
    lines += ["| Measure | Count |", "| --- | --- |"]
    lines.append(f"| Classified repositories | {len(repos)} |")
    lines.append(f"| Canonical (authority-bearing) | {sum(1 for r in repos if r['canonical'])} |")
    lines.append(f"| Observed, unclassified | {len(observed)} |")
    if observation:
        lines.append(f"| Observed in organization on {observation['observed_at']} | {observation['total_observed']} |")
    lines.append("")

    by_class = defaultdict(list)
    for entry in repos:
        by_class[entry["primary_class"]].append(entry)
    lines += ["## Classified repositories by class", ""]
    for cls in sorted(by_class):
        lines += [f"### `{cls}`", "", "| Repository | Visibility | Lifecycle | Canonical | Purpose |", "| --- | --- | --- | --- | --- |"]
        for entry in sorted(by_class[cls], key=lambda e: e["repository"].casefold()):
            lines.append(
                f"| {link(entry['repository'])} | {entry['visibility']} | `{entry['lifecycle']}` | "
                f"{'yes' if entry['canonical'] else 'no'} | {entry['purpose']} |"
            )
        lines.append("")

    lifecycle = Counter(entry["lifecycle"] for entry in repos)
    lines += ["## Lifecycle distribution", "", "| Lifecycle | Count |", "| --- | --- |"]
    for state, count in sorted(lifecycle.items()):
        lines.append(f"| `{state}` | {count} |")
    lines.append("")

    pending = [e for e in repos if e.get("topology_status") or e.get("classification_status")]
    lines += ["## Decisions awaiting an owner", ""]
    if pending:
        lines += ["| Repository | Status field | Value |", "| --- | --- | --- |"]
        for entry in sorted(pending, key=lambda e: e["repository"].casefold()):
            for field in ("topology_status", "classification_status"):
                if entry.get(field):
                    lines.append(f"| {link(entry['repository'])} | `{field}` | `{entry[field]}` |")
    else:
        lines.append("None recorded.")
    lines.append("")

    conditions = [e for e in repos if e.get("extraction_trigger") or e.get("retirement_condition")]
    lines += ["## Extraction triggers and retirement conditions", ""]
    if conditions:
        lines += ["| Repository | Extraction trigger | Retirement condition |", "| --- | --- | --- |"]
        for entry in sorted(conditions, key=lambda e: e["repository"].casefold()):
            lines.append(
                f"| {link(entry['repository'])} | {entry.get('extraction_trigger') or '—'} | "
                f"{entry.get('retirement_condition') or '—'} |"
            )
    else:
        lines.append("None recorded.")
    lines.append("")

    lines += ["## Observed, unclassified repositories", ""]
    if observation:
        lines += [
            f"Observed on {observation['observed_at']} via {observation['source']}. "
            "These rows record existence, visibility, and creation date only. Purpose, owner, lifecycle, class, "
            "authority, and canonical status are **not** inferred from names; each stays `OBSERVED_UNCLASSIFIED` "
            "until an owner-approved classification is merged.",
            "",
        ]
        if observation["registered_not_observed"]:
            lines.append(
                "Registered but not observed in the listing on that date: "
                + ", ".join(f"`{name}`" for name in observation["registered_not_observed"])
                + ". Absence from a listing is an observation, not an archive or deletion decision."
            )
            lines.append("")
    if observed:
        lines += ["| Repository | Visibility | Created | Observed | Status |", "| --- | --- | --- | --- | --- |"]
        for entry in observed:
            lines.append(
                f"| {link(entry['repository'])} | {entry['visibility']} | {entry['created_at'][:10]} | "
                f"{entry['observed_at']} | `{entry['status']}` |"
            )
    else:
        lines.append("None recorded.")
    lines.append("")

    lines += ["## Policy", "", data["unclassified_policy"], ""]
    return "\n".join(lines)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--registry", type=Path, default=REGISTRY)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    parser.add_argument("--check", action="store_true", help="Fail if the output file is not in sync")
    args = parser.parse_args(argv)
    data = json.loads(args.registry.read_text(encoding="utf-8"))
    rendered = render(data)
    if args.check:
        current = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
        if current != rendered:
            print(f"FAIL: {args.output} is out of sync with {args.registry}; run scripts/portfolio_report.py", file=sys.stderr)
            return 1
        print(f"Portfolio projection in sync: {args.output}")
        return 0
    args.output.write_text(rendered, encoding="utf-8")
    print(f"Wrote {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
