#!/usr/bin/env python3
"""Render docs/PORTFOLIO.md from .quirk/repositories.json.

The Markdown file is a projection. The truthful topology inventory is the
source. `--check` fails when the committed projection differs from what the
inventory renders, so the two cannot drift. Standard library only;
deterministic output.
"""

import argparse
import json
import sys
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / ".quirk" / "repositories.json"
OUTPUT = ROOT / "docs" / "PORTFOLIO.md"
GITHUB = "https://github.com/"


def cell(value):
    """Escape a value for use inside a pipe-delimited Markdown table cell."""
    text = str(value).replace("\r\n", "\n").replace("\r", "\n")
    return text.replace("|", "\\|").replace("\n", "<br>")


def link(repository):
    return f"[`{repository}`]({GITHUB}{repository})"


def owner_label(owner):
    if owner["state"] == "identified":
        return owner["name"]
    return "open"


def render(data):
    lines = [
        "# Quirk Systems portfolio",
        "",
        "<!-- Generated by scripts/portfolio_report.py from .quirk/repositories.json. Do not edit; edit the registry. -->",
        "",
        f"Registry version: `{data['registry_version']}`  ",
        f"Snapshot: `{data['snapshot']}`  ",
        f"Authority: `{data['authority']}`  ",
        "Authority effect: **none**. This page projects the truthful topology inventory; it classifies nothing by itself.",
        "",
    ]
    repos = data["repositories"]
    scope = data["scope"]

    lifecycle = Counter(entry["lifecycle"] for entry in repos)
    owner_states = Counter(entry["owner"]["state"] for entry in repos)
    lines += ["## Summary", "", "| Measure | Count |", "| --- | --- |"]
    lines.append(f"| Inventory repositories | {len(repos)} |")
    lines.append(f"| Organization repositories | {scope['expected_organization_repository_count']} |")
    lines.append(f"| Adjacent repositories | {scope['expected_adjacent_repository_count']} |")
    for state in sorted(lifecycle):
        lines.append(f"| Lifecycle `{state}` | {lifecycle[state]} |")
    for state in sorted(owner_states):
        lines.append(f"| Owner state `{state}` | {owner_states[state]} |")
    lines.append("")
    lines += ["Adjacency rule:", "", scope["adjacent_repository_selection_rule"], ""]

    by_class = defaultdict(list)
    for entry in repos:
        by_class[entry["primary_class"]].append(entry)
    lines += ["## Repository inventory by class", ""]
    for cls in sorted(by_class):
        lines += [
            f"### `{cls}`",
            "",
            "| Repository | Scope | Visibility | Lifecycle | Owner | Canonical responsibility |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
        for entry in sorted(by_class[cls], key=lambda item: item["repository"].casefold()):
            lines.append(
                f"| {link(entry['repository'])} | `{entry['scope']}` | {cell(entry['visibility'])} | `{entry['lifecycle']}` | "
                f"`{cell(owner_label(entry['owner']))}` | {cell(entry['canonical_responsibility'])} |"
            )
        lines.append("")

    lines += ["## Decisions awaiting an owner", ""]
    open_owner = [entry for entry in repos if entry["owner"]["state"] == "open"]
    if open_owner:
        lines += [
            "| Repository | Scope | Class | Why it remains open |",
            "| --- | --- | --- | --- |",
        ]
        for entry in sorted(open_owner, key=lambda item: item["repository"].casefold()):
            lines.append(
                f"| {link(entry['repository'])} | `{entry['scope']}` | `{entry['primary_class']}` | {cell(entry['extraction_or_retirement_rule'])} |"
            )
    else:
        lines.append("None recorded.")
    lines.append("")

    lines += ["## Boundaries and evidence", ""]
    lines += [
        "| Repository | Consumers and dependencies | Deployment/security boundary | Evidence anchors |",
        "| --- | --- | --- | --- |",
    ]
    for entry in sorted(repos, key=lambda item: (item["scope"], item["repository"].casefold())):
        anchors = "; ".join(f"[{cell(anchor['label'])}]({cell(anchor['url'])})" for anchor in entry["evidence_anchors"])
        consumers = cell("; ".join(entry["consumers_and_dependencies"]))
        lines.append(
            f"| {link(entry['repository'])} | {consumers} | {cell(entry['deployment_security_boundary'])} | {anchors} |"
        )
    lines.append("")
    return "\n".join(lines)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--registry", type=Path, default=REGISTRY)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    parser.add_argument("--check", action="store_true", help="Fail if the output file is not in sync")
    args = parser.parse_args(argv)
    data = json.loads(args.registry.read_text(encoding="utf-8"))
    rendered = render(data)
    if args.check:
        current = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
        if current != rendered:
            print(f"FAIL: {args.output} is out of sync with {args.registry}; run scripts/portfolio_report.py", file=sys.stderr)
            return 1
        print(f"Portfolio projection in sync: {args.output}")
        return 0
    args.output.write_text(rendered, encoding="utf-8")
    print(f"Wrote {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
